# Generated by Django 5.1 on 2024-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
