# Generated by Django 5.1 on 2024-10-04 15:12

from django.db import migrations, models


def consolidate_analytics(apps, schema_editor):
    Analytics = apps.get_model('taskManager', 'Analytics')
    users = Analytics.objects.values('user_id').distinct()

    for user in users:
        user_id = user['user_id']
        user_analytics = Analytics.objects.filter(user_id=user_id)

        if user_analytics.count() > 1:
            first_record = user_analytics.first()

            total_tasks_completed = sum([record.tasks_completed for record in user_analytics])
            total_tasks_created = sum([record.tasks_created for record in user_analytics])
            total_high_priority = sum([record.high_priority_tasks for record in user_analytics])
            total_medium_priority = sum([record.medium_priority_tasks for record in user_analytics])
            total_low_priority = sum([record.low_priority_tasks for record in user_analytics])

            first_record.tasks_completed = total_tasks_completed
            first_record.tasks_created = total_tasks_created
            first_record.high_priority_tasks = total_high_priority
            first_record.medium_priority_tasks = total_medium_priority
            first_record.low_priority_tasks = total_low_priority
            first_record.save()

            user_analytics.exclude(pk=first_record.pk).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_alter_analytics_unique_together_alter_analytics_date'),
    ]

    operations = [
        migrations.RunPython(consolidate_analytics),

        migrations.RemoveField(
            model_name='analytics',
            name='id',
        ),
        migrations.AlterField(
            model_name='analytics',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
